// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2YvcDYRWpgcGx2myHiJscDf_3zKsf_NY',
    appId: '1:1089598716077:web:c1c3e92aeb25f82eee6e24',
    messagingSenderId: '1089598716077',
    projectId: 'csc-outreach-agent',
    authDomain: 'csc-outreach-agent.firebaseapp.com',
    storageBucket: 'csc-outreach-agent.firebasestorage.app',
    measurementId: 'G-5KSLLL588B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMDp4jwMd8vLHGTRTCJOT_BwyKocbBdvk',
    appId: '1:1089598716077:android:caaada28086ea600ee6e24',
    messagingSenderId: '1089598716077',
    projectId: 'csc-outreach-agent',
    storageBucket: 'csc-outreach-agent.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCptaNm5AIPEHqlTNrez9rOgl_i_0NsKWU',
    appId: '1:1089598716077:ios:3d7a2eaa9ce119dfee6e24',
    messagingSenderId: '1089598716077',
    projectId: 'csc-outreach-agent',
    storageBucket: 'csc-outreach-agent.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCptaNm5AIPEHqlTNrez9rOgl_i_0NsKWU',
    appId: '1:1089598716077:ios:3d7a2eaa9ce119dfee6e24',
    messagingSenderId: '1089598716077',
    projectId: 'csc-outreach-agent',
    storageBucket: 'csc-outreach-agent.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2YvcDYRWpgcGx2myHiJscDf_3zKsf_NY',
    appId: '1:1089598716077:web:ac2e995e11a3fc81ee6e24',
    messagingSenderId: '1089598716077',
    projectId: 'csc-outreach-agent',
    authDomain: 'csc-outreach-agent.firebaseapp.com',
    storageBucket: 'csc-outreach-agent.firebasestorage.app',
    measurementId: 'G-H2L35PB6KV',
  );
}
